### ISSUE TITLE
Graphics Jitter When Using Torch Server

### ISSUE THREAD

**Issue by Blaquestone** [austinvaness/CameraLCD#2]
Disabling the Camera to LCD using its in-game menu stops this from happening. Not the server owner; let me know if there's anything else I can give.
https://i.gyazo.com/5ff526c22fa94a58971ac53de0780830.gif

**Comment by austinvaness** [comment]
Sorry I missed this bug report. I was never able to reproduce this bug, but it looks like an LOD issue I fixed a while ago.

**Comment by Omega-563** [comment]
I still have this issue, seems to be linked with the render range.
Experiencing it in my creative world when I have another grid within the render range in meters of a grid with a camera displaying to a screen.

When I turn down the render range the LOD flickering stops until I move the camera grid within that range of another grid.
Only grids within the render range seem to flicker.
Workaround is just to keep the render range low.
